using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

namespace Localize;

public class Localization
{
	private string cultureName = "en-US";

	private Dictionary<string, TextCollection> textCollections = new Dictionary<string, TextCollection>();

	private static readonly Localization _instance = new Localization();

	public string CultureName
	{
		get
		{
			return cultureName;
		}
		set
		{
			if (textCollections.ContainsKey(value))
			{
				cultureName = value;
			}
			else
			{
				Debug.LogWarning((object)("Culture name not found " + value));
			}
		}
	}

	public static Localization Instance => _instance;

	private Localization()
	{
		textCollections.Add("en-US", new TextCollection(new List<string>
		{
			"Toggle HD",
			"Toggle FullScreen <O>",
			"Show Chat <T>",
			"Show Players <TAB>",
			"Show Help",
			"Play Mode <P>",
			"Edit Mode <P>",
			"Edit Cube <1>",
			"Delete Cube <2>",
			"Paint Cube <3>",
			"Spraypaint Cube <4>",
			"Toggle Grid Snap Size <G>",
			"Toggle Drawplane <F>",
			"Toggle Show Logic Cubes <L>",
			"Change Cube Material <R>",
			"Open Inventory <I>",
			"Create New Model <N>",
			"Publish",
			"Health",
			"Center Gun",
			"Start Point",
			"Flag",
			"Battery",
			"Time Trigger",
			"Toggle Box",
			"Negate Box",
			"And Box",
			"Pressure Plate",
			"Light",
			"Bomb",
			"Fire",
			"Smoke",
			"Text Message",
			"Respawn <K>",
			"Impulse Gun",
			"Bazooka",
			"Lava",
			"Ice",
			"Poison",
			"Parkour",
			"Move Drawplane Up <PgUp>",
			"Move Drawplane Down <PgDown>",
			"Rail Gun",
			"Mutant pickup: kill non-mutants by touching them",
			string.Empty,
			"Bouncy",
			"Skybox",
			"Remove from inventory",
			"Sword",
			"Change Teams",
			"Object Enabler",
			"Shotgun",
			"FlameThrower",
			"Pulse Box",
			"Randomizer",
			"Sound Emitter",
			"Water Plane",
			"T-Pose",
			"Idle",
			"Run",
			"Jump",
			"Die",
			"Take avatar screenshot",
			"Reset avatar",
			"Control Room",
			"Open Shop Inventory",
			"Press M to show Menu",
			"Release TAB to hide Menu",
			"Press M to hide Menu",
			"Open Avatar shop",
			"Add Collectible",
			"Disconnected",
			"Connecting",
			"Joining",
			"Joined",
			"Leaving",
			"Disconnecting",
			"Exception",
			"TimeoutDisconnect",
			"SendError",
			"Joining",
			"Fetching Materials",
			"Fetching Item Types",
			"Fetching Ownership Types",
			"Fetching Inventory",
			"Fetching Shop Inventory",
			"Fetching Avatar Shop Inventory",
			"Fetching Game Snapshot",
			"Fetching User List",
			"Fetching Friends",
			"Fetching Team List",
			"Selecting Team",
			"Setting Team",
			"Fetching Streaming Assets",
			"Creating Avatar",
			"Creating Avatar Body",
			"Setting Actor Ready",
			"Playing",
			"Leaving",
			"Connection",
			"Game",
			"Players: {0}",
			"Player",
			"Blue Team",
			"Red Team",
			"Green Team",
			"Yellow Team",
			"Score",
			"Fetching Active Avatar",
			"{0} killed {1} with {2}",
			"a Center Gun",
			"a Bazooka",
			"a RailGun",
			"{0} comitted suicide",
			"{0} hit the ground too hard",
			"{0}  was killed by the environment",
			"a Sword",
			"{0} was blown to bits",
			"{0} burned to death",
			"{0} fell off the world",
			"Mutant",
			"a Shotgun",
			"a FlameThrower",
			"{0} was crushed by cubes",
			"{0} was killed by a ghost",
			"This item can't be used in this game type.",
			"Restricted",
			"Are you sure\nwant to delete?",
			"Restricted",
			"Screenshot Taken!",
			"This will remove any changes you've made.\nAre you sure?",
			"Reset Avatar",
			"Select Type",
			"Type",
			"Can't create blueprint with 0 children.",
			"Error",
			"Delete Child ?",
			"Delete",
			"Float value",
			"Change Value",
			"Failed to parse new value",
			"Int Value",
			"String Value",
			"Delete Data?",
			"Since you are previewing this item,\nit will be deleted when you exit.",
			"Insert Preview",
			"Click \"Get Gold\" in the website menu\nto add more gold to your account.",
			"Insufficient Funds",
			"Not enough silver to purchase product",
			"Not enough funds to purchase product",
			"An error occured:\n",
			"You are not authorized to\npublish this planet",
			"Show Outline",
			"Object Enabler",
			"Hide",
			"The sound in this sound emitter is no longer available.\nIf you pick another sound, you can not change it back",
			"Notice",
			"Select Modifier",
			"Modifier",
			"Speed",
			"Moving Platform",
			"Rotation Speed",
			"Rotator",
			"Once",
			"Trigger Box",
			"Only one team in world.",
			"Change Team",
			"Please Register",
			"Register",
			"Project with planetId '{0}' does not exist",
			"Error with the Internet and/or database connection...",
			"No game servers found!",
			"Can't request friendship from yourself!",
			"Buy Model ?",
			"Fullscreen is not supported in \nInternet Explorer version 8+.\n\nPlease use another browser,\n to use fullscreen.",
			"Yes",
			"No",
			"Ok",
			"Save",
			"Discard",
			"Cancel",
			"You forgot these things:\n\nNo name entered.\nNo woID entered.",
			"You forgot these things:\n\nNo name entered.",
			"You forgot these things:\n\nNo woID entered.",
			"Item Shop",
			"Avatar Shop",
			"Publish Your Game",
			"Material Shop",
			"Sound shop",
			"Continue",
			"You cannot delete the last spawn-point.\nAll Projects must have at least one",
			"Apply",
			"Connection Exception\nReconnect?",
			"Connection Lost.\nReconnect?",
			"Connection Timeout.\nReconnect?",
			"Item purchased",
			"Undefined fail!",
			"You cannot purchase the item,\nsince you are the owner",
			"The item to purchase\nwas not found",
			"The item is already in your inventory",
			"Successfully added model to your inventory",
			"Failed to add to inventory",
			"Failed to create item",
			"You are not the creator of this model.\n\nYou can only add models to your inventory, if they are created by you",
			"You are not the creator of this model.\n\nBuy the model to add it to your Inventory\nPrice: {0} silver",
			"The item is already in your inventory",
			"Prototype not found",
			"You are not authorized to join planet '{0}' in edit mode",
			"Successfully published planet",
			"You are not authorized to publish this planet",
			"Unhandled returnCode",
			"Purchase",
			"Price",
			"Please Wait ...",
			"Preview",
			"Gravity",
			"Max Players",
			"Round Time",
			"Adventure",
			"Chat",
			"Coop",
			"Capture The Flag",
			"Deathmatch",
			"Reach The Flag",
			"Time Trial",
			"Are You Sure?",
			"Publish To Facebook",
			"Prev",
			"Next",
			"Material Selection",
			"Blue",
			"Green",
			"Red",
			"Intensity",
			"Range",
			"Text",
			"Text Size",
			"Disabled Time",
			"Enabled Time",
			"Seconds",
			"Fog",
			"Sun Angle",
			"Mute",
			"Delay",
			"Duration",
			"Change",
			"Shop",
			"Join",
			"Congratulations",
			"You collected all the collectibles!",
			"Play Again",
			"Do you want to play again?",
			"Game Over",
			"Time's up",
			"No items available for purchase",
			"Advanced\nLogic",
			"Blueprint",
			"Logic",
			"Pickups",
			"Premium\nModels",
			"New Model",
			"Size",
			"Back",
			"You don't own any Blueprints.\nGet some from the shop!",
			"You don't own any Premium Models.\nGet some from the shop!",
			"Models",
			"Click To Control ...",
			"Send",
			"GameMsgs",
			"Settings",
			"Edit Model",
			"Delete",
			"Clone",
			"Reset Logic",
			"Add To Inventory",
			"Add New Avatar",
			"There was a server communication problem. Try again!",
			"Respawn Now!",
			"Respawn in",
			"Press",
			"to purchase",
			"Accessories Shop",
			"Accessories Inventory",
			"{0} failed to rocketjump",
			"Product",
			"Fetching Credit Status",
			"Synchronizing Game Time",
			"Description",
			"Name",
			"This will remove the model from your inventory",
			"Info",
			"Sell",
			"Manage",
			"Item Difference",
			"Sell Item",
			"Update Item",
			"Remove Item",
			"'{0}' is now on the marketplace.",
			"Failed to put '{0}' on the marketplace.",
			"Please make sure all the required information is entered",
			"Your model is not different enough compared to the original model",
			"Comparing...",
			"'{0}' updated on marketplace.",
			"Failed to update '{0}'.",
			"Removed '{0}' from marketplace.",
			"Failed to remove '{0}' from marketplace.",
			"Rent",
			"Extend",
			"{0} seconds",
			"{0} minutes",
			"{0} hours",
			"{0} days",
			"{0} secs",
			"{0} mins",
			"Do you want to extend?",
			"Item can't be renewed and will now be removed.",
			"Remove",
			"Fetching Streaming Asset Inventory",
			"Rent Period Expired",
			"Expired",
			"You don't own any\nAvatar Accessories.\n\nGet some from the shop!",
			"Avatar\nAccessories",
			"has expired.",
			"Why not get this great item from the shop?",
			"Attach to avatar now?",
			"Product expired",
			"Round Cube",
			"Winning Condition",
			"Reach The Flag First",
			"Eliminate Other Players",
			"Collect Stars",
			"Reach Highest Altitude",
			"Reach Lowest Altitude",
			"Reach The Flag First",
			"Eliminate Most Players",
			"Collect The Stars",
			"Reach The Highest Altitude",
			"Reach The Lowest Altitude",
			"There is already an object of this type in the game. Only one per game is allowed",
			"Flag Reached By ",
			"All Stars Collected By ",
			"Oculus settings",
			"{0} was eliminated by an Oculus",
			"Aggression"
		}));
		textCollections.Add("da-DK", new TextCollection(new List<string>
		{
			"Skift Til/Fra HD",
			"Skift Til/Fra Fuldskærm <O>",
			"Vis Chat <T>",
			"Vis Spillere <TAB>",
			"Vis Hjælp",
			"Spille  tilstand <P>",
			"Redigerings tilstand <P>",
			"Rediger Kube <1>",
			"Slet Kube <2>",
			"Mal Kube <3>",
			"Spraymal Kube <4>",
			"Tænd/Sluk Gitter Størrelse <G>",
			"Tænd/Sluk Tegneplan <F>",
			"Tænd/Sluk Vis Logik Kuber <L>",
			"Ændre Kube Materiale <R>",
			"Åben Inventory <I>",
			"Lav Ny Model <N>",
			"Udgiv",
			"Liv",
			"Center Gevær",
			"Start Punkt",
			"Flag",
			"Batteri",
			"Tidsudløser",
			"Tænd/Sluk Boks",
			"Negations Boks",
			"Og Boks",
			"Tryk Plade",
			"Lys",
			"Bombe",
			"Ild",
			"Røg",
			"Tekst Besked",
			"Genopliv <K>",
			"Impuls Gevær",
			"Bazooka",
			"Lava",
			"Is",
			"Gift",
			"Parkour",
			"Flyt Tegneplanet op <PgUp>",
			"Flyt Tegneplanet ned <PgDown>",
			"Rail Gun",
			"Mutant pickup: Dræb ikke-mutanter ved at røre dem",
			string.Empty,
			"Hoppe",
			"Himmelboks",
			"Fjern fra inventory",
			"Sværd",
			"Gendan Hold",
			"Objekt kontakt",
			"Haglgevær",
			"Flammekaster",
			"Puls Box",
			"Tilfældighedsgenerator",
			"Lydkilde",
			"Vand plan",
			"T-Posering",
			"Stå",
			"Løbe",
			"Hoppe",
			"Dø",
			"Tag avatar Billede",
			"Nulstil avatar",
			"Kontrol Rum",
			"Åben Butiks Inventory",
			"Tryk M for Menu",
			"Slip TAB for at gemme Menu",
			"Tryk M for at gemme Menu",
			"Åben Avatar butik",
			"Tilføj Samlerobjekt",
			"Forbindelse afbrudt",
			"Forbinder",
			"Tilslutter",
			"Tilsluttet",
			"Forlader",
			"Afbryder Forbindelse",
			"Undtagelse",
			"Timeout afbrydelse",
			"Send Fejl",
			"Tilslutter",
			"Henter Materialer",
			"Henter objekt typer",
			"Henter Ejerskabstyper",
			"Henter Beholdning",
			"Henter Butikslager",
			"Henter Avatar Butikslager",
			"Henter Spiltilstand",
			"Henter Brugerliste",
			"Henter Venner",
			"Henter Holdliste",
			"Vælger Hold",
			"Sætter Hold",
			"Henter Streaming Aktiver",
			"Danner Avatar",
			"Danner Avatar Krop",
			"Sætter Spiller Klar",
			"Spiller",
			"Forlader",
			"Forbindelse",
			"Spil",
			"Spillere: {0}",
			"Spiller",
			"Blåt hold",
			"Rødt hold",
			"Grønt hold",
			"Gult hold",
			"Point",
			"Henter Active Avatar",
			"{0} dræbte {1} med {2}",
			"et center gevær",
			"en bazooka",
			"en railgun",
			"{0} begik selvmord",
			"{0} ramte jorden for hårdt",
			"{0} blev dræbt af verden",
			"et sværd",
			"{0} blev sprunget i luften",
			"{0} blev brændte op",
			"{0} faldt af verden",
			"mutant",
			"et haglgevær",
			" en flammekaster",
			"{0} blev mast",
			"{0} blev dræbt af et spøgelse",
			"Dette object kan ikke bruges i denne spiltype",
			"Spærret",
			"Er du sikker på\nat du vil slette?",
			"Spærret",
			"Skærmprint Taget!",
			"Denne handling vil slette de ændringer du har lavet\nEr du sikker?",
			"Nulstil Avatar",
			"Vælg type",
			"Type",
			"Kan ikke danne et blueprint med 0 børn",
			"Fejl",
			"Slet barn ?",
			"Slet",
			"Decimal værdi",
			"Ændre værdi",
			"Kunne ikke fortolke den nye værdi",
			"Heltals værdi",
			"Streng værdi",
			"Slet Data?",
			"Da du kun afprøver dette objekt,\nvil det blive slettet når du forlader spillet.",
			"Indsæt prøveobjekt",
			"Klik \"Hent Guld\" i website menuen\nfor at få mere guld ind på din konto.",
			"Utilstrækkelige midler",
			"Do har ikke nok sølv",
			"Ikke tilstrækkelige midler til at købe produktet",
			"Der opstod en fejl:\n {0}",
			"Du er ikke autoriseret til\nat udgive denne planet",
			"Vis omrids",
			"Objekt kontakt",
			"Skjul",
			"Lyden i denne lydkilde er ikke længere tilgængelig.\nHvis du vælger en anden lyd, kan du ikke omgøre valget",
			"Bemærk",
			"Vælg modifikator",
			"Modifikator",
			"Fart",
			"Bevægelig platform",
			"Rotationshastighed",
			"Rotator",
			"Engangsaktivering",
			"Udløser kasse",
			"Kun et hold i spillet.",
			"Skift hold",
			"Registrer venligst",
			"Registrere",
			"Projektet med planetId '{0}' eksisterer ikke",
			"Fejl med internet og/eller database forbindelse...",
			"Kunne ikke finde nogen spilservere!",
			"Du kan blive ven med dig selv!",
			"Køb model ?",
			"Fuldskærm er ikke understøttet i \nInternet Explorer version 8+.\n\nVenligst prøv en anden browser,\n for at bruge fuldskærm.",
			"Ja",
			"Nej",
			"Ok",
			"Gem",
			"Smid væk",
			"Annuller",
			"Du glemte følgende :\n\nNavn.\nWoid.",
			"Du glemte følgende:\n\nNavn.",
			"Du glemte følgende:\n\nWoid.",
			"Spilobjekt butik",
			"Avatar butik",
			"Udgiv dit spil",
			"Materiale butik",
			"Lyd butik",
			"Fortsæt",
			"Du kan ikke slette det sidste start punkt.\nAlle spil skal have mindst et",
			"Anvend",
			"Forbindelse Exception\nForbind igen?",
			"Forbindelsen er mistet.\nForbind igen?",
			"Forbindelse timeout.\nForbind igen?",
			"vare købt",
			"Udefineret fejl!",
			"Du kan ikke købe varen,\nda du allerede ejer den",
			"Varen blev ikke fundet",
			"Varen eksisterer allerede i dit inventory",
			"Tilføjede model til dit inventory",
			"Kunne ikke tilføje til inventory",
			"Kunne ikke danne objekt",
			"Du er ikke skaber af denne model.\n\nDu kan kun tilføje modeller til dit inventory, som du selv har bygget",
			"Du er ikke skaber af denne model.\n\nKøb denne model for at tilføje den til dit inventory\nPris: {0} sølv",
			"Varen er allerede i dit inventory",
			"Prototypen blev ikke fundet",
			"Du er ikke autoriseret til at deltage i planet '{0}' i redigeringstilstand",
			"Planeten er blevet udgivet",
			"Du er ikke autoriseret til at udgive denne planet.",
			"Uhåndteret returkode",
			"Køb",
			"Pris",
			"Vent venligst ...",
			"Prøv spilleobjekt",
			"Tyngdekraft",
			"Max spillere",
			"Runde Tid",
			"Udforskning",
			"Chat",
			"Co-op",
			"Capture The Flag",
			"Deathmatch",
			"Reach The Flag",
			"På tid",
			"Er du sikker?",
			"Post på Facebook",
			"Forrige",
			"Næste",
			"Materiale valg",
			"Blå",
			"Grøn",
			"Rød",
			"Intensitet",
			"Rækkevidde",
			"Tekst",
			"Tekst str.",
			"Slukket tid",
			"Tændt tid",
			"Sekunder",
			"Tåge",
			"Sol vinkel",
			"Lydløs til/fra",
			"Forsinkelse",
			"Varighed",
			"Ny værdi",
			"Butik",
			"Tilslut",
			"Tillykke",
			"Du har samlet alle samleobjekterne!",
			"Spil Igen",
			"Ville du spille igen?",
			"Game Over",
			"Tiden er gået",
			"Ingen varer tilsalg",
			"Avanceret\nLogik",
			"Blueprint",
			"Logik",
			"Opsamling",
			"Premium\nModeller",
			"Ny Model",
			"Størrelse",
			"Tilbage",
			"Du ejer ikke nogen Blueprints.\nKøb nogen i butikken!",
			"Du ejer ikke nogen Premium modeller.\nKøb nogen i butikken!",
			"Modeller",
			"Klik for at spille ...",
			"Send",
			"Spil besk.",
			"Indstillnger",
			"Rediger Model",
			"Slet",
			"Klon",
			"Nulstil Logik",
			"Tilføj Inventory",
			"Tilføj ny Avatar",
			"Der var et problem med at nå serveren. Prøv igen!",
			"Genopliv nu!",
			"Genopliver om",
			"Tryk",
			"for at købe",
			"Tilbehørsbutik",
			"Tilbehør Inventory",
			"{0} skød sig selv med en bazooka",
			"Produkt",
			"Henter kredit status",
			"Synchronizing game time",
			"Beskrivelse",
			"Navn",
			"This will remove the model from your inventory",
			"Info",
			"Sell",
			"Manage",
			"Item Difference",
			"Sell Item",
			"Update Item",
			"Remove Item",
			"'{0}' is now on the marketplace.",
			"Failed to put '{0}' on the marketplace.",
			"Please make sure all the required information is entered",
			"Your model is not different enough compared to the original model",
			"Comparing...",
			"'{0}' updated on marketplace.",
			"Failed to update '{0}'.",
			"Removed '{0}' from marketplace.",
			"Failed to remove '{0}' from marketplace.",
			"Rent",
			"Extend",
			"{0} seconds",
			"{0} minutes",
			"{0} hours",
			"{0} days",
			"{0} secs",
			"{0} mins",
			"Do you want to extend?",
			"Item can't be renewed and will now be removed.",
			"Remove",
			"Fetching Streaming Asset Inventory",
			"Rent Period Expired",
			"Expired",
			"You don't own any\nAvatar Accessories.\n\nGet some from the shop!",
			"Avatar\nAccessories",
			"has expired.",
			"Why not get this great item from the shop?",
			"Attach to avatar now?",
			"Product expired",
			"Runde cube",
			"Vinder form",
			"Nå Flaget Først",
			"Eliminer andre spillere",
			"Find Stjerner",
			"Nå Højest Op",
			"Nå Længest Ned",
			"Nå Flaget Først",
			"Eliminer Flest Andre Spillere",
			"Find Flest Stjerner",
			"Nå Højest Op",
			"Nå Længest Ned",
			"Der er allerede et object af denne type i spillet. Det er kun tilladt at have en enkelt af denne type per spil",
			"Flag nået af ",
			"Alle stjerner samlet af "
		}));
		textCollections.Add("nb-NO", new TextCollection(new List<string>
		{
			"Veksle HD",
			"Bytte til fullskjerm <o>",
			"Vis Chat <T>",
			"Vis Spillere <TAB>",
			"Vis Hjelp",
			"Spillemodus <P>",
			"Redigeringsmodus <P>",
			"Rediger Cube <1>",
			"Slett Cube <2>",
			"Male Cube <3>",
			"Spraylakkere Cube <4>",
			"Veksle Grid Snap Size <G>",
			"Veksle Drawplane <F>",
			"Veksle Show Logic Cubes <L>",
			"Endre Cube Material <R>",
			"Åpne inventar <I>",
			"Opprett ny modell <N>",
			"Publiser",
			"Helse",
			"Senter Gun",
			"Startpunkt",
			"Flagg",
			"Batteri",
			"Tid Trigger",
			"Veksle eske",
			"Negere eske",
			"Og eske",
			"Pressure Plate",
			"Lys",
			"Bomb",
			"Ild",
			"Røyk",
			"Tekstmelding",
			"Genstart <K>",
			"Impulse Gun",
			"Bazooka",
			"Lava",
			"Is",
			"Gift",
			"Parkour",
			"Flytt tegneplan opp <PgUp>",
			"Flytt tegneplan ned <PgDown>",
			"Rail Gun",
			"Mutant pickup: drepe ikke-mutanter ved å berøre dem",
			string.Empty,
			"Bouncy",
			"Himmeleske",
			"Fjern fra lageret",
			"Sverd",
			"Endre lag",
			"Objekt Enabler",
			"Hagle",
			"Flammekaster",
			"Puls eske",
			"Randomizer",
			"Lydsender",
			"Vann plan",
			"T-Positur",
			"Hvilemodus",
			"Kjør",
			"Hoppe",
			"Dø",
			"Ta avatar skjermbilde",
			"Tilbakestille avatar",
			"Kontroll rom",
			"Åpne Shop Varelager",
			"Trykk M å vise Meny",
			"Slipp TAB for å skjule menyen",
			"Trykk M for å skjule menyen",
			"Åpen Avatar butikk",
			"Legg Samlegjenstander",
			"Frakoblet",
			"Tilkobling",
			"Bli med",
			"Ble",
			"Leaving",
			"Frakobling",
			"Unntak",
			"Timeout Frakobling",
			"Send feil",
			"Bli med",
			"Henter Materialer",
			"Henter elementtyper",
			"Henter eiertyper",
			"Henter inventar",
			"Henter butikk Varelager",
			"Henter avatar butikk varelager",
			"Henter spillet SnapShot",
			"Henter Liste over brukere",
			"Henter venner",
			"Henter teamet liste",
			"Velge lag",
			"Stille lag",
			"Henting Streaming Eiendeler",
			"Opprette Avatar",
			"Opprette Avatar Bod",
			"Stille Actor Klar",
			"Spille",
			"Forlater",
			"Tilkobling",
			"Spillet",
			"Spillere: {0}",
			"Spiller",
			"Blått lag",
			"Rødt lag",
			"Grønt lag",
			"Gult lag",
			"Resultat",
			"Henter aktiv avatar",
			"{0} drepte {1} med {2}",
			"et senter Gun",
			"en bazooka",
			"et strålevåpen",
			"{0} comitted selvmord",
			"{0} traff bakken for hardt",
			"{0} ble drept av miljøet",
			"et sverd",
			"{0} ble sprengt i biter",
			"{0} brent til døde",
			"{0} falt av verden",
			"Mutant",
			"en hagle",
			"en flammekasterr",
			"{0} ble knust av kuber",
			"{0} ble drept av et spøkelse",
			"Dette elementet kan ikke brukes i denne type spill.",
			"Begrenset",
			"Er du sikker på at du \nønsker å slette?",
			"Begrenset",
			"Skjermbilde tatt!",
			"Dette vil fjerne alle endringer du har gjort. \nEr du sikker ?",
			"Tilbakestille Avatar",
			"Velg type",
			"Type",
			"Kan ikke opprette blåkopi med 0 barn.",
			"feil",
			"Slett Child?",
			"Slett",
			"Float verdi",
			"Endre verdi",
			"Klarte ikke å analysere ny verdi",
			"Int verdi",
			"Strengverdi",
			"Slette data?",
			"Siden du forhåndsviser dette elementet, \n det vil bli slettet når du avslutter.",
			"Sett Preview",
			"Klikk \"få gull \" på nettstedet menyen \n å legge til flere gull til din konto.",
			"Utilstrekkelige midler",
			"Ikke nok sølv til å kjøpe produktet",
			"Ikke nok midler til å kjøpe produktet",
			"Det oppstod en feil: \n",
			"Du er ikke autorisert til å \n publisere denne planeten",
			"Vis Outline",
			"Objekt enabler",
			"Skjul",
			"Lyden i denne lyden emitter er ikke lenger tilgjengelig. \n Hvis du velge en annen lyd, kan du ikke endre det tilbake",
			"Legg merke til",
			"Velg Modifier",
			"Modifier",
			"Fart",
			"Flytte Platform",
			"Rotasjonshastighet",
			"Rotator",
			"En gang",
			"Trigger eske",
			"Kun ett lag i verden.",
			"Endre lag",
			"Vennligst registrer",
			"Registrer",
			"Prosjekt med planetId '{0}' eksisterer ikke",
			"Feil med internett og / eller database tilkobling ...",
			"Ingen spillservere funnet!!",
			"Kan ikke be om vennskap fra deg selv!",
			"Kjøpe model?",
			"Fullskjerm støttes ikke i \n Internet Explorer versjon 8 +. \n \n Vennligst bruk en annen nettleser for å \n bruke fullskjerm.",
			"Ja",
			"Nei",
			"Ok",
			"Spare",
			"Kast",
			"Avbryt",
			"Du glemte disse tingene:. \n \n Ingen navn oppgitte \n Ingen woID inn.",
			"Du glemte disse tingene:. \n \n Ingen navn oppgitte.",
			"Du glemte disse tingene:. \n \n Ingen woID inn.",
			"Element butikk",
			"Avatar butikk",
			"Publiser spillet",
			"Materiale butikk",
			"Lyd butikk",
			"Fortsett",
			"Du kan ikke slette de siste spawn-point. \n Alle Prosjekter må ha minst én",
			"Påfør",
			"Tilkobling Unntak \n Koble?",
			"Tilkobling tapt.\nKoble?",
			"Tilkobling Timeout.\nKoble?",
			"Vare kjøpt",
			"Udefinert feil!",
			"Du kan ikke kjøpe elementet, \n siden du er eieren",
			"Elementet for å kjøpe \n ble ikke funnet",
			"Elementet er allerede i varelager",
			"Lagt modell til inventar",
			"Failed to add to inventory",
			"Kunne ikke legge til inventar",
			"Du er ikke skaperen av denne modellen. \n \n Du kan bare legge modeller til inventar, hvis de er opprettet av deg",
			"Du er ikke skaperen av denne modellen \n \n Kjøp modellen å legge den til din beholdning \n Pris:. {0} sølv",
			"Elementet er allerede i varelager",
			"Prototype ikke funnet",
			"Du er ikke autorisert til å delta planet {0} i redigeringsmodus",
			"Er publisert planet",
			"Du er ikke autorisert til å publisere denne planeten",
			"Ubehandlet returkode",
			"Kjøp",
			"Pris",
			"Vennligst vent ...",
			"Forhåndsvisning",
			"Gravity",
			"Maks antall spillere",
			"Rundetid",
			"Adventure",
			"Chat",
			"Coop",
			"Capture The Flag",
			"Deathmatch",
			"Nå flagget",
			"Time Trial",
			"Er du sikker?",
			"Publiser til Facebook",
			"Forrige",
			"Neste",
			"Materiale utvalg",
			"Blå",
			"Grønn",
			"Rød",
			"Intensitet",
			"Rekkevidde",
			"Tekst",
			"Tekst størrelse",
			"Deaktivert Tid",
			"Aktivert Tid",
			"Sekunder",
			"Tåke",
			"Sol vinkel",
			"Slå av lyden",
			"Forsinkelse",
			"Varighet",
			"Endre",
			"Butikk",
			"Delta",
			"Gratulerer",
			"Du har samlet alle samleobjekter!",
			"Spill igjen",
			"Vil du spille igjen?",
			"Ingen vinnere",
			"Tid er opp",
			"Ingen elementer tilgjengelig for kjøp",
			"Avansert\nLogik",
			"Blueprint",
			"Logik",
			"Pickups",
			"Premium\nModeller",
			"Ny modell",
			"Størrelse",
			"Tilbake",
			"Du eier ikke noen Blueprints.\nFå noe fra butikken!",
			"Du eier ikke noen premium modeller.\nFå noe fra butikken!",
			"Modeller",
			"Klikk for å styre ...",
			"Send",
			"spillMeld.",
			"Innstillinger",
			"Redigere Model",
			"Slett",
			"Klone",
			"Tilbakestille Logic",
			"Legg til inventar",
			"Legg til ny Avatar",
			"Det var en server kommunikasjonsproblem. Prøv igjen!",
			"Respawn nå!",
			"Respawn om",
			"Trykk",
			"å kjøpe",
			"Tilbehør butikk",
			"Tilbehør inventar",
			"{0} mislyktes i å rocketjump",
			"Produkt",
			"Henter kredit status",
			"Synchronizing game time",
			"Description",
			"Name",
			"This will remove the model from your inventory",
			"Info",
			"Sell",
			"Manage",
			"Item Difference",
			"Sell Item",
			"Update Item",
			"Remove Item",
			"'{0}' is now on the marketplace.",
			"Failed to put '{0}' on the marketplace.",
			"Please make sure all the required information is entered",
			"Your model is not different enough compared to the original model",
			"Comparing...",
			"'{0}' updated on marketplace.",
			"Failed to update '{0}'.",
			"Removed '{0}' from marketplace.",
			"Failed to remove '{0}' from marketplace.",
			"Rent",
			"Extend",
			"{0} seconds",
			"{0} minutes",
			"{0} hours",
			"{0} days",
			"{0} secs",
			"{0} mins",
			"Do you want to extend?",
			"Item can't be renewed and will now be removed.",
			"Remove",
			"Fetching Streaming Asset Inventory",
			"Rent Period Expired",
			"Expired",
			"You don't own any\nAvatar Accessories.\n\nGet some from the shop!",
			"Avatar\nAccessories",
			"has expired.",
			"Why not get this great item from the shop?",
			"Attach to avatar now?",
			"Product expired",
			"Round Cube",
			"Winning Condition",
			"Reach The Flag First",
			"Get Most Kills",
			"Find Most Collectibles",
			"Reach Highest Altitude",
			"Reach Lowest Altitude",
			"Reach the flag before time is up,\nor another player reaches it",
			"Kill as many as you can before time is up",
			"Find as many collectibles as you can\nbefore time is up.\nFinding all collectibles ends the round",
			"Reach the highest altitude before time is up",
			"Reach the lowest altitude before time is up",
			"There is already an object of this type in the game. Only one per game is allowed",
			"Flag Reached By ",
			"All Stars Collected By "
		}));
		textCollections.Add("sv-SE", new TextCollection(new List<string>
		{
			"Växla HD",
			"Växla FullScreen <O>",
			"Visa Chat <T>",
			"Visa Spelare <TAB>",
			"Visa Hjälp",
			"Spelläge <P>",
			"Redigeringsläge <P>",
			"Redigera Cube <1>",
			"Ta bort Cube <2>",
			"Måla Cube <3>",
			"Sprayfärg Cube <4>",
			"Växla rutnät Snap storlek  <G>",
			"Växla Rita plan <F>",
			"Växla kuber Visa Logic <L>",
			"Ändra Cube material <R>",
			"Öppna Inventory <I>",
			"Skapa nya modell <N>",
			"Publicera",
			"Hälsa",
			"Center Gun",
			"Startpunkt",
			"Flagga",
			"Batteri",
			"Tid Trigger",
			"Växla Box",
			"Förneka Box",
			"Och Box",
			"Tryckplatta",
			"Ljus",
			"Bomb",
			"Eld",
			"Rök",
			"Text meddelande",
			"Respawn <K>",
			"Impuls Gun",
			"Bazooka",
			"Lava",
			"Is",
			"Gift",
			"Parkour",
			"Flytta rita plan upp <PgUp>",
			"Flytta rita plan ned <PgDown>",
			"Rail Gun",
			"Mutant pickup: döda icke-mutanter genom att röra vid dem",
			string.Empty,
			"Bouncy",
			"Himmel",
			"Bort från lagret",
			"Svärd",
			"Ändra lag",
			"Objekt Enabler",
			"Hagelgevär",
			"Eldkastare",
			"Puls box",
			"Randomizer",
			"Ljudsändare",
			"Vatten Plan",
			"T-Pose",
			"Idle",
			"Löpa",
			"Hoppa",
			"Dö",
			"Ta Avatar skärmdump",
			"Återställ avatar",
			"Kontroll rum",
			"Öppna butik Lagar",
			"Tryck på M för att visa menyn",
			"Släpp TAB för att dölja menyn",
			"Tryck M för att dölja menyn",
			"Öppna Avatar butiken",
			"Lägg Collectible",
			"Frånkopplad",
			"Anslutning",
			"Joining",
			"Blev",
			"Lämnar",
			"Koppla",
			"Undantag",
			"TidsgränsKoppla",
			"SkickaFel",
			"Joining",
			"Hämtar material",
			"Hämtar objekttyper",
			"Hämtar ägande Typer",
			"Hämtar lager",
			"Hämtar butik lagar",
			"Hämtar Avatarbutiklagar",
			"Hämtar spelögonblicksbild",
			"Hämtar Använderlista",
			"Hämtar vänner",
			"Hämtar laglista",
			"Välja lag",
			"Ställa lag",
			"Hämtar Streaming Tillgångar",
			"Skapa Avatar",
			"Skapa Avatar Body",
			"Ställa aktör Klar",
			"Spela",
			"Lämnar",
			"Anslutning",
			"Spel",
			"Spelare: {0}",
			"Spelare",
			"Blå lag",
			"Röd lag",
			"Grön lag",
			"Gul lag",
			"Betyg",
			"Hämtar Aktiv Avatar",
			"{0} dödade {1} med {2}",
			"en Center Gun",
			"en bazooka",
			"en railgun",
			"{0} lämade självmord",
			"{0} slog i marken för hårt",
			"{0} dödades av miljön",
			"ett svärd",
			"{0} blåstes till bitar",
			"{0} brändes till dödsh",
			"{0} föll världen",
			"Mutant",
			"en hagelgevär",
			"en eldkastare",
			"{0} krossades av kuber",
			"{0} dödades av ett spöke",
			"Denna produkt kan inte användas i det här spelet typ.",
			"Begränsas",
			"Är du säker på \n vill radera?",
			"Begränsas",
			"Skärmdump Taken!",
			"Detta kommer att ta bort alla ändringar du har gjort. \n Är du säker?",
			"Återställ Avatar",
			"Välj typ",
			"Typ",
			"Kan inte skapa blåkopia med 0 barn.",
			"Fel",
			"Ta bort barn ?",
			"Ta borte",
			"Float värde",
			"Ändra värde",
			"Misslyckades med att tolka nytt värde",
			"Int värde",
			"Strängvärde",
			"Ta bort data?",
			"Eftersom du förhandsgranskar denna post \n kommer att tas bort när du avslutar.",
			"Infoga Förhandsgranska",
			"Klicka \"få guld \" på webbplatsen menyn \n lägga mer guld till ditt konto.",
			"Otillräckliga fonder",
			"Inte nog silver att köpa produkten",
			"Inte tillräckligt med pengar för att köpa produkten",
			"Ett fel uppstod: \n",
			"Du har inte behörighet att \n publicera den här planeten",
			"Visa Disposition",
			"Objekt Enabler",
			"Göm",
			"Ljudet i detta ljud sändare är inte längre tillgänglig. \n Om du väljer ett annat ljud, kan du inte ändra tillbaka",
			"Kallelse",
			"Välj ändra",
			"Ändra",
			"Hastighet",
			"Rörlig plattform",
			"Rotationshastighet",
			"Rotator",
			"När",
			"Trigger Box",
			"Endast ett lag i världen.",
			"Ändra lag",
			"Vänligen registrera",
			"Registrera",
			"Projekt med planetId '{0}' finns inte",
			"Fel med Internet och / eller databasanslutning ...",
			"Inga spelservrar hittade!",
			"Kan inte begära vänskap från dig!",
			"Köp Modell ?",
			"Fullskärm stöds inte i \n Internet Explorer version 8 +. \n \n Använd en annan webbläsare, \n använda helskärm.",
			"Ja",
			"Nej",
			"Ok",
			"Spara",
			"Släng",
			"Avbryt",
			"Du glömde dessa saker: \n \n Inget namn anges \n Ingen woID in.",
			"Du glömde dessa saker:\n\nInget namn anges.",
			"Du glömde dessa saker:\n\nIngen woID in.",
			"Produkt butik",
			"Avatar butik",
			"Publicera ditt spel",
			"Material butik",
			"Ljud butik",
			"Fortsätt",
			"Du kan inte ta bort den sista spawn-punkt. \n Alla projekt måste ha minst en",
			"Ansök",
			"Anslutning Undantag \n Anslut?",
			"Anslutning förlorade. \n Återanslut?",
			"Tidsgräns för anslutning. \n Återanslut?",
			"Vara som köpts",
			"Odefinierad misslyckas!",
			"Du kan inte köpa artikeln, \n eftersom du är ägare",
			"Objektet att köpa \n hittades inte",
			"Objektet finns redan i ditt lager",
			"Lagts modell till ditt lager",
			"Det gick inte att lägga till lager",
			"Det gick inte att skapa objekt",
			"Du är inte skaparen av denna modell. \n \n Du kan bara lägga modeller ditt lager, om de är skapade av dig",
			"Du är inte skaparen av denna modell \n \n Köp modellen för att lägga till din Inventering \n Pris:. {0} silver",
			"Objektet finns redan i ditt lager",
			"Prototyp hittades inte",
			"Du har inte behörighet att ansluta planet '{0}' i redigeringsläge",
			"Framgångsrikt publicerade planet",
			"Du har inte behörighet att publicera den här planeten",
			"Ohanterat returkoden",
			"Köp",
			"Pris",
			"Var god vänta ...",
			"Förhandsgranska",
			"Tyngdkraft",
			"Max  spelare",
			"Varvtid",
			"Äventyr",
			"Samtal",
			"Coop",
			"Capture The Flag",
			"Deathmatch",
			"Nå flaggan",
			"Time Trial",
			"Är du säker?",
			"Publicera till Facebook",
			"Föregående",
			"Nästa",
			"Materialval",
			"Blå",
			"Grön",
			"Röd",
			"Intensitet",
			"Räckvidd",
			"Text",
			"Textstorlek",
			"Obrukbar tid",
			"Aktiverad tid",
			"Sekunder",
			"Dimma",
			"Sol Vinkel",
			"Mute",
			"Fördröjning",
			"Varaktighet",
			"Ändra",
			"Butik",
			"Gå",
			"Grattis",
			"Du samlat alla samlarobjekt!",
			"Spela igen",
			"Vill du spela igen?",
			"Inga Vinnare",
			"Tiden är ute",
			"Inga objekt tillgängliga för inköp",
			"Avancerad\nLogik",
			"Blåkopia",
			"Logik",
			"Pickups",
			"Premium\nModeller",
			"Ny modell",
			"Storlek",
			"Tillbaka",
			"Du äger inte några blåkopia.\nFå lite från butiken!",
			"Du äger inte någon premium modeller.\nFå lite från butiken!",
			"Modeller",
			"Klicka för att kontrollera ...",
			"Skicka",
			"GameMdl",
			"Inställningar",
			"Redigera modell",
			"Ta bort",
			"Klon",
			"Återställ Logik",
			"Lägg till lager",
			"Lägg till ny Avatar",
			"Det uppstod ett serverfel kommunikationsproblem. Försök igen!",
			"Respawn nu!",
			"respawn om",
			"Tryck",
			"att köpa",
			"Tillbehör butik",
			"Tillbehör lager",
			"{0} misslyckades att rocketjump",
			"Produkt",
			"Hämtar kredit status",
			"Synchronizing game time",
			"Description",
			"Name",
			"This will remove the model from your inventory",
			"Info",
			"Sell",
			"Manage",
			"Item Difference",
			"Sell Item",
			"Update Item",
			"Remove Item",
			"'{0}' is now on the marketplace.",
			"Failed to put '{0}' on the marketplace.",
			"Please make sure all the required information is entered",
			"Your model is not different enough compared to the original model",
			"Comparing...",
			"'{0}' updated on marketplace.",
			"Failed to update '{0}'.",
			"Removed '{0}' from marketplace.",
			"Failed to remove '{0}' from marketplace.",
			"Rent",
			"Extend",
			"{0} seconds",
			"{0} minutes",
			"{0} hours",
			"{0} days",
			"{0} secs",
			"{0} mins",
			"Do you want to extend?",
			"Item can't be renewed and will now be removed.",
			"Remove",
			"Fetching Streaming Asset Inventory",
			"Rent Period Expired",
			"Expired",
			"You don't own any\nAvatar Accessories.\n\nGet some from the shop!",
			"Avatar\nAccessories",
			"has expired.",
			"Why not get this great item from the shop?",
			"Attach to avatar now?",
			"Product expired",
			"Round Cube",
			"Winning Condition",
			"Reach The Flag First",
			"Get Most Kills",
			"Find Most Collectibles",
			"Reach Highest Altitude",
			"Reach Lowest Altitude",
			"Reach the flag before time is up,\nor another player reaches it",
			"Kill as many as you can before time is up",
			"Find as many collectibles as you can\nbefore time is up.\nFinding all collectibles ends the round",
			"Reach the highest altitude before time is up",
			"Reach the lowest altitude before time is up",
			"There is already an object of this type in the game. Only one per game is allowed",
			"Flag Reached By ",
			"All Stars Collected By "
		}));
		textCollections.Add("pt", new TextCollection(new List<string>
		{
			"HD",
			"Tela Cheia <O>",
			"Mostrar Chat <T>",
			"Mostrar Jogadores <TAB>",
			"Mostrar Ajuda",
			"Modo de Jogo <P>",
			"Modo Edição <P>",
			"Editar Cubo <1>",
			"Deletar Cubo <2>",
			"Pintar Cubo <3>",
			"Pintar com Spray <4>",
			"Alternar Tamanho da Grade <G>",
			"Plano de Desenho <F>",
			"Mostrar Cubos de Lógica <L>",
			"Mudar Material do Cubo <R>",
			"Abrir Inventário <I>",
			"Criar Novo Modelo <N>",
			"Publicar",
			"Vida",
			"Canhão Central",
			"Ponto Inicial",
			"Bandeira",
			"Bateria",
			"Gatilho de Tempo",
			"Ligar/Desl. Caixa",
			"Negar Caixa",
			"E a Caixa",
			"Botão de pressão",
			"Luz",
			"Bomba",
			"Fogo",
			"Fumaça",
			"Mensagem de Texto",
			"Renascer <K>",
			"Canhão de Impulso",
			"Bazuca",
			"Lava",
			"Gelo",
			"Veneno",
			"Parkour",
			"Plano de Desenho para cima <PgUp>",
			"Plano de desenho para baixo <PgDown>",
			"Canhão elétrico",
			"Vírus mutante: mate não-mutantes ao tocar neles",
			string.Empty,
			"Elástico",
			"Skybox",
			"Remover do inventário",
			"Espada",
			"Mudar de Time",
			"Ativador de Objetos",
			"Shotgun",
			"Lança-Chamas",
			"Caixa de Pulsar",
			"Randomizador",
			"Emissor de Som",
			"Plano d'água",
			"Pose T",
			"Parado",
			"Correr",
			"Pular",
			"Morrer",
			"Tirar screenshot do avatar",
			"Redefinir avatar",
			"Sala de controle",
			"Abrir Loja",
			"Aperte M para o Menu",
			"Solte TAB para esconder menu",
			"Aperte M para esconder Menu",
			"Abrir loja do avatar",
			"Adicionar Colecionável",
			"Desconectado",
			"Conectando",
			"Entrando",
			"Entrou",
			"Saindo",
			"Desconectado",
			"Excessão",
			"Desconectado",
			"Erro no Envio",
			"Entrando",
			"Buscando materiais",
			"Buscando tipos de itens",
			"Buscando Tipos de Posse",
			"Buscando Inventário",
			"Buscando Inventário da Loja",
			"Buscando Inventário da Loja de avatar",
			"Buscando Snapshot do jogo",
			"Buscando Lista de Usuários",
			"Buscando Amigos",
			"Buscando Lista de Equipe",
			"Selecionando Equipe",
			"Configurando Equipe",
			"Buscando Objetos de Streaming",
			"Criando Avatar",
			"Criando corpo de avatar",
			"Confugurando Ator",
			"Jogando",
			"Saindo",
			"Conexão",
			"Jogo",
			"Jogadores: {0}",
			"Jogador",
			"Time Azul",
			"Time Vermelho",
			"Time Verde",
			"Time Amarelo",
			"Pontuação",
			"Buscando Avatar ativo",
			"{0} matou {1} com {2}",
			"um Canhão Central",
			"uma Bazuca",
			"um Canhão Elétrico",
			"{0} cometeu suicídio",
			"{0} acertou o chão com força demais",
			"{0} foi morto pelo ambiente",
			"uma espada",
			"{0} se transformou em bits",
			"{0} virou churrasquinho",
			"{0} caiu do mundo",
			"Mutante",
			"uma Shotgun",
			"um Lança-chamas",
			"{0} foi esmagado por cubos",
			"{0} foi morto por um fantasma",
			"Esse item não pode ser usado nesse tipo de jogo.",
			"Restrito",
			"Tem certeza\nque quer deletar?",
			"Restrito",
			"ScreenShot tirada!",
			"Isso removerá suas modificações.\nTem certeza?",
			"Redefinir Avatar",
			"Selecionar Tipo",
			"Tipo",
			"Não é possível criar plantas com 0 itens.",
			"Erro",
			"Deletar Item?",
			"Deletar",
			"Valor Flutuante",
			"Mudar Valor",
			"A análise do novo valor falhou",
			"Valor da variável",
			"Valor da String",
			"Deletar ?",
			"Como esta é a pré-visualização do item,\n ele será deletado quando você sair.",
			"Inserir Pre-visualização",
			"Clique \"Obter ouro\" no menu do site\npara adicionar mais ouro à sua conta.",
			"Fundos Insuficientes",
			"Prata insuficiente para comprar esse produto",
			"Fundos insuficientes para comprar esse produto",
			"Um erro ocorreu:\n",
			"Você não está autorizado a\npublicar esse planeta",
			"Mostrar Contornos",
			"Ativador de Objetos",
			"Esconder",
			"O som desse emissor de som não está mais disponível.\nSe você escolher outro som, não poderá voltar para este.",
			"Aviso",
			"Selecionar Modificador",
			"Modificador",
			"Velocidade",
			"Movendo Plataforma",
			"Velocidade de rotação",
			"Rotacionador",
			"Uma vez",
			"Caixa de gatilho",
			"Só uma equipe no mundo.",
			"Mudar Equipe",
			"Por favor registre-se",
			"Registrar",
			"Projeto com planetId '{0}' não existe",
			"Erro com a internet e/ou conexão com a database...",
			"Não foram encontrados servidores!",
			"Não se pode enviar pedidos de amizade a si mesmo!",
			"Comprar Modelo?",
			"Modo tela cheia não é suportado em\nInternet Explorer versão 8+.\n\nPor favor escolha outro navegador,\n para usar a tela cheia.",
			"Sim",
			"Não",
			"Ok",
			"Salvar",
			"Descartar",
			"Cancelar",
			"Você esqueceu de:\n\nColocar nome.\nColocar woID.",
			"Você esqueceu de:\n\nColocar nome.",
			"Você esqueceu de:\n\nColocar woID.",
			"Loja de itens",
			"Loja de avatares",
			"Publicar seu jogo",
			"Loja de Materiais",
			"Loja de sons",
			"Continuar",
			"Você não pode deletar o último ponto de renascimento.\nProjetos precisam de pelo menos um",
			"Aplicar",
			"Problema de Conexão\nReconectar?",
			"Connection Perdida.\nReconnectar?",
			"Problema de Conexão\nReconectar?",
			"Item comprado",
			"Falha Desconhecida!",
			"Você não pode comprar o item,\npois você é o dono",
			"O item a ser comprado\nnão foi encontrado",
			"Esse item já está no seu inventário",
			"Adicionado em seu inventário com sucesso",
			"Falhou ao adicionar no inventário",
			"Criação do item falhou",
			"Você não é o autor desse modelo.\n\nSó é possível colocar no inventário modelos que foram criadors por você",
			"Você não é o criador desse modelo.\n\nCompre-o para adicioná-lo em seu inventário.\nPreço: {0} pratas.",
			"Esse item já está no seu inventário",
			"Protótipo não encontrado",
			"Você não está autorizado a entrar no planeta '{0}' no modo edição",
			"Planeta publicado com sucesso",
			"Você não está autorizado a publicar esse planeta",
			"Código de retorno desconhecido",
			"Comprar",
			"Preço",
			"Por Favor espere ...",
			"Prever",
			"Gravidade",
			"Max. de Jogadores",
			"Tempo do Round",
			"Aventura",
			"Chat",
			"Coop",
			"Capture a bandeira",
			"Último Sobrevivente",
			"Alcance a bandeira",
			"Desafio do Tempo",
			"Tem certeza?",
			"Publicar no Facebook",
			"Anterior",
			"Próximo",
			"Selecionar Material",
			"Azul",
			"Verde",
			"Vermelho",
			"Intensidade",
			"Alcance",
			"Texto",
			"Tamanho do Texto",
			"Tempo desativado",
			"Tempo ativado",
			"Segundos",
			"Neblina",
			"Ângulo do Sol",
			"Mudo",
			"Intervalo",
			"Duração",
			"Mudar",
			"Loja",
			"Entrar",
			"Parabéns",
			"Você conseguiu todos os colecionáveis!",
			"Jogar novamente",
			"Quer jogar novamente?",
			"Fim de Jogo",
			"Tempo acabou",
			"Não há itens disponíveis para compra",
			"Avençado\nLogica",
			"Planta",
			"Logica",
			"Ativáveis",
			"Modelos\nPremium",
			"Novo Modelo",
			"Tamanho",
			"Voltar",
			"Você não possui Plantas.\nConsiga algumas na loja!",
			"Você não possui Modelos Premium\nConsiga alguns na loja!",
			"Modelos",
			"Clique para Controlar ...",
			"Enviar",
			"Mensagens no jogo",
			"Configurações",
			"Editar Modelo",
			"Deletar",
			"Clonar",
			"Redefinir Logica",
			"Adicionar ao inventário",
			"Adicionar Novo Avatar",
			"Houve um problema de comunicação com o servidor. Tente novamente!",
			"Renascer Agora!",
			"Renasce em",
			"Aperte",
			"para comprar",
			"Loja de Acessórios",
			"Inventário de Acessórios",
			"O foguete de {0} falhou",
			"Produto",
			"Listando Status do Crédito",
			"Sincronizando tempo de Jogo",
			"Descrição",
			"Nome",
			"Isso removerá o modelo do seu inventário",
			"Informações",
			"Vender",
			"Administrar",
			"Diferença do Item",
			"Vender Item",
			"Atualizar Item",
			"Remover Item",
			"'{0}' está à venda.",
			"Falha! '{0}' não foi colocado à venda.",
			"Cheque se as informações necessárias foram preenchidas",
			"Seu modelo não é diferente o suficiente do modelo original",
			"Comparando...",
			"'{0}' foi atualizado no mercado.",
			"Falha ao atualizar '{0}'.",
			"'{0}' foi removido do mercado.",
			"Falha ao remover '{0}' do mercado.",
			"Alugar",
			"Extender",
			"{0} segundos",
			"{0} minutos",
			"{0} horas",
			"{0} dias",
			"{0} segs",
			"{0} mins",
			"Você quer extender?",
			"Esse item não pode ser renovado, então será removido.",
			"Remover",
			"Listando inventário de Assets para Streams",
			"Período de aluguel expirou",
			"Expirado",
			"Você não possui\nAcessórios de Avatar.\n\nConsiga alguns na Loja!",
			"Avatares\nAcessórios",
			"expirou.",
			"Por que não comprar esse ótimo item na loja?",
			"Colocar em seu avatar?",
			"Produto expirou",
			"Cubo de Rounds",
			"Condição de Vitória",
			"Alcançar a Bandeira Primeiro",
			"Eliminar os outros jogadores",
			"Coletar Estrelas",
			"Alcançar o ponto mais alto",
			"Alcançar o ponto mais baixo",
			"Alcançar a Bandeira Primeiro",
			"Eliminar mais Jogadores",
			"Colete as Estrelas",
			"Alcance o ponto Mais Alto",
			"Alcance o ponto Mais Baixo",
			"Já há um objeto desse tipo. É permitido apenas um por projeto.",
			"Bandeira Alcançada por ",
			"Estrelas Coletadas por",
			"Configurações do Oculus",
			"{0} foi eliminado por um Oculus",
			"Agressivo"
		}));
		textCollections.Add("fi", new TextCollection(new List<string>
		{
			"Vaihda HD", "Vaihda Kokonäyttöön <O>", "Näytä keskustelu <T>", "Näytä pelaajat ", "Näytä apua", "Pelitila ", "Muokkaustila ", "Muokkaa kuutioita <1>", "Poista kuutioita <2>", "Maalaa kuutioita <3>",
			"Spraymaalaa kuutioita <4>", "Vaihda kuutioiden tarttumakokoa <G>", "Vaihda piirtotasoa <F>", "Vaihda, näkyvätkö logiikkakuutiot <L>", "Vaihda kuution materiaalia <R>", "Avaa tavaraluettelo <I>", "Luo uusi esine <N>", "Julkaise", "Terveys", "Konekivääri",
			"Aloituspiste", "Lippu", "Akku", "Aikakatkaisin", "Päälle ja pois-laatikko", "Vastakkaislaatikko", "Ja-laatikko", "Painelaatta", "Valo", "Pommi",
			"Tuli", "Savu", "Teksti", "Respawnaa", "Impulssiase", "Sinko", "Laava", "Jää", "Happo", "Parkour",
			"Siirrä piirtotasoa ylös ", "Siirrä piirtotasoa alas ", "Sniper", "Mutantti: Tapa ei-mutantteja koskettamalla heitä", "NULL", "Trampoliini", "Taivaansäätäjä", "Poista tavaravalikosta", "Miekka", "Vaihda puolta",
			"Esineenluoja", "Haulikko", "Liekinheitin", "Pulssilaatikko", "Randomisoija", "Äänilaatikko", "Vesitaso", "T-asento", "Paikallaanoleva", "Juoksu",
			"Hyppy", "Kuolema", "Ota hahmokuva", "Resetoi hahmo", "Tarkkaamo", "Avaa kaupan valikko", "Paina M avataksesi valikon", "Vapauta TAB piilottaaksesi valikon", "Paina M piilottaaksesi valikon", "Avaa hahmokauppa",
			"Lisää keräiltävä", "Yhteys katkennut", "Yhdistetään", "Liitytään", "Liittynyt", "Lähtee", "Katkaistaan yhteys", "Poikkeus", "TimeoutDisconnect", "SendError",
			"Liitytään", "Haetaan materiaaleja", "Haetaan esinetyyppejä", "Haetaan omistustyyppejä", "Haetaan esinevalikkoa", "Haetaan kauppavalikkoa", "Haetaan hahmokauppavalikkoa", "Haetaan peliä", "Haetaan pelaajalistaa", "Haetaan ystäviä",
			"Haetaan joukkuelistaa", "Valitsee joukkuetta", "Asettaa joukkuetta", "Haetaan striimauseriä", "Luodaan hahmoa", "Luodaan hahmoa", "Asetetaan pelaajaa valmiiksi", "Pelaamassa", "Lähtee", "Yhteys",
			"Peli", "Pelaajat: {0}", "Pelaaja", "Sininen joukkue", "Punainen joukkue", "Vihreä joukkue", "Keltainen joukkue", "Pisteet", "Haetaan aktiivihahmoa", "{0} tappoi {1} {2}lla",
			"Konekivääri", "Sinko", "Sniperi", "{0} palasi spawnille", "{0} osui maahan liian kovaa", "{0} kuoli ympäristön vuoksi", "Miekka", "{0} räjähti", "{0} kuoli tulessa", "{0} tippui pois kartalta",
			"Mutantti", "Haulikko", "Liekinheitin", "{0} musertui kuutioihin", "{0} kuoli haamuihin", "Tätä esinettä ei voi käyttää tässä pelityypissä.", "Rajoitettu", "Oletko varma?", "Rajoitettu", "Hahmokuva otettu!",
			"Tämä poistaa kaikki muutokset mitä olet tehnyt. Oletko varma?", "Resetoi hahmo", "Valitse tyyppi", "Tyyppi", "Ei voi luoda erikoisesinettä 0 pienoisosalla.", "Virhe", "Poista pienoisosa?", "Poista", "Leijumismäärä", "Muutoksen määrä",
			"Uuden arvon jäsentäminen epäonnistui", "Alustava määrä", "Merkkijonon määrä", "Poista data?", "Koska olet vain esikatselemassa tätä esinettä, se poistetaan kun lähdet.", "Lisää esikatselu", "Klikkaa \"Osta Kultaa\" nettisivun valikosta lisätäksesi Goldia käyttäjätilillesi.", "Riittämättömät varat", "Ei tarpeeksi hopeaa ostaa tätä tuotetta", "Ei tarpeeksi varoja ostaa tuotetta",
			"Virhe ilmeni:\n", "Sinulla ei ole lupaa julkaista tätä projektia", "Näytä ääriviivat", "Esineenluoja", "Piilota", "Ääni, joka tässä äänilaatikossa oli, ei ole enää saatavilla. Jos valitset toisen äänen, et voi vaihtaa sitä takaisin.", "Huomaa", "Valitse muokkaaja", "Muokkaaja", "Nopeus",
			"Liikkuva alusta", "Pyörimisnopeus", "Pyörittäjä", "Kerran", "Liipaisinlaatikko", "Vain yksi joukkue maailmassa.", "Vaihda puolta", "Rekisteröidy", "Rekisteröidy", "Projektia planeettaIDllä '{0}' ei ole olemassa",
			"Virhe Internetin, tai datakeskuksen yhteydessä...", "Peliservereitä ei löytynyt!", "Et voi pyytää itseäsi ystäväksi!", "Osta esine?", "Internet explorerin versiot 8 eteenpäin eivät tue kokonäyttötilaa, käytä toista selainta päästäksesi kokonäyttötilaan", "Kyllä", "Ei", "Ok", "Tallenna", "Hylkää",
			"Peruuta", "Unohdit nämä:\n\nEi nimeä kirjoitettu.\nEi woIDtä kirjoitettu.", "Unohdit nämä:\n\nEi nimeä kirjoitettu.", "Unohdit nämä:\n\nEi woIDtä kirjoitettu.", "Esinekauppa", "Hahmokauppa", "Julkaise pelisi", "Materiaalikauppa", "Äänikauppa", "Jatka",
			"Et voi poistaa viimeistä aloituspistettä.\nKaikissa projekteissa pitää olla ainakin yksi", "Käytä", "Yhteyden poikkeus\nYhdistä uudelleen?", "Yhteys katkennut.\nYhdistä uudelleen?", "Yhteys aikakatkaistiin.\nYhdistä uudelleen?", "Esine ostettu", "Määrittelemätön epäonnistuminen!", "Et voi ostaa esinettä,\nkoska olet sen omistaja", "Ostettavaa esinettä\nei löytynyt", "Esine on jo tavaraluettelossasi",
			"Esine lisättiin onnistuneesti esinevalikkoosi", "Tavaraluetteloon tallentaminen epäonnistui", "Esineen luominen epäonnistui", "Et ole tämän esineen luoja.\n\nVoit lisätä esineen tavaraluetteloosi vain, jos se on sinun tekemäsi", "Et ole tämän esineen tekijä.\n\nOsta se lisätäksesi sen tavaraluetteloosi\nHinta: {0} Hopeaa", "Esine on jo tavaraluettelossasi", "Prototyyppiä ei löytynyt", "Sinut on sallittu liittyä projektiin '{0}' muokkaustilassa", "Onnistuneesti julkaistu projekti", "Sinulla ei ole lupaa julkaista tätä projektia",
			"Epäkäsitelty palautuskoodi", "Osta", "Hinta", "Odota...", "Esikatsele", "Painovoima", "Maksimit pelaajat", "Erän aika", "Seikkaile", "Keskustelu",
			"Yhteistyö", "Kaappaa lippu", "Kuolemanottelu", "Pääse lipulle", "Aikahaaste", "Oletko varma?", "Julkaise Facebookiin", "Edellinen", "Seuraava", "Materiaalin valinta",
			"Sininen", "Vihreä", "Punainen", "Voimakkuus", "Säde", "Teksti", "Tekstin koko", "Aika epäaktiivisena", "Aika aktiivisena", "Sekunttia",
			"Sumu", "Auringon kulma", "Mykistä", "Viive", "Kesto", "Muuta", "Kauppa", "Liity", "Onnittelut", "Keräsit kaikki keräivtävät",
			"Pelaa uudelleen", "Haluatko pelata uudelleen?", "Ei voittajia", "Aika on loppu", "Ei esineitä ostettaviksi", "Edistynyt\nlogiikka", "Erikoisesine", "Logiikka", "Aseet", "Premium\nesineet",
			"Uusi esine", "Koko", "Takaisin", "Et omista yhtään erikoisesinettä.\nHanki niitä kaupasta!", "Et omista yhtään premiumesinettä.\nHanki niitä kaupasta!", "Esineet", "Klikkaa pelataksesi ...", "Lähetä", "PeliViestit", "Asetukset",
			"Muokkaa esinettä", "Poista", "Monista", "Resetoi logiikka", "Lisää tavaravalikkoon", "Lisää uusi hahmo", "Palvelinyhteysongelma ilmeni. Yritä uudelleen!", "Uudelleenspawnaa nyt!", "Uudelleenspawnaukseen", "Paina",
			"ostaaksesi", "Tarvikekauppa", "Tarvikeluettelo", "{0} epäonnistui rakettihypyssä", "Tuote", "Haetaan rahastatusta", "Synkronoidaan peliaikaa", "Kuvaus", "Nimi", "Tämä poistaa esineen tavaraluettelostasi",
			"Info", "Myy", "Hallinnoi", "Esineen erilaisuus", "Myy esine", "Päivitä esine", "Poista esine", "'{0}' on nyt Kaupassa.", "'{0}' myyminen epäonnistui.", "Varmista että kaikki vaadittava tieto on kirjoitettu",
			"Sinun esineesi ei ole tarpeeksi erilainen alkuperäiseen esineeseen verrattuna", "Vertaillaan...", "'{0}' on päivitetty Kaupassa.", "'{0}' päivitys epäonnistui.", "'{0}' on poistettu Kaupasta.", "'{0}' poistaminen Kaupasta epäonnistui", "Vuokraa", "Pidennä", "{0} sekuntia", "{0} minuuttia",
			"{0} tuntia", "{0} päivää", "{0} sekunttia", "{0} minuuttia", "Haluatko pidentää?", "Esinettä ei voi uusia, ja se poistetaan nyt.", "Poista", "Haetaan striimaus esitysinventaariota", "Vuokrauksen aika vanhentunut", "Vanhentunut",
			"Et omista yhtään\nhahmotarviketta.\n\nHanki niitä kaupasta!", "Hahmotarvikkeet", "on vanhentunut.", "Miksi et ostaisi tätä mahtavaa esinettä kaupasta?", "Kiinnitä hahmoon nyt?", "Tuote vanhentunut"
		}));
		textCollections.Add("pl-PL", new TextCollection(new List<string>
		{
			"Włącz HD", "Włącz Pełny Ekran <O>", "Pokaż Czat <T>", "Pokaż Graczy <TAB>", "Pokaż Pomoc", "Tryb Grania <P>", "Tryb Edycji <P>", "Edycja Bloków <1>", "Usuwanie Bloków <2>", "Malowanie Bloków <3>",
			"Malowanie Sprayem Bloków", "Ustaw Dokładność Łączenia <G>", "Włącz Płaszczyznę <F>", "Pokazywanie Bloków Logicznych <L>", "Zmiana Materiału Bloku <R>", "Otwórz Ekwipunek <I>", "Stwórz Nowy Model <N>", "Opublikuj", "Życie", "Center Gun",
			"Punkt Startowy", "Flaga", "Bateria", "Wyzwalanie Czasowe", "Blok Przełączania", "Blok Negacji", "Blok And", "Płyta Naciskowa", "Światło", "Bomba",
			"Ogień", "Dym", "Wiadomość Tekstowa", "Respawn <K>", "Impulse Gun", "Bazooka", "Lawa", "Lód", "Trucizna", "Parkour",
			"Posuń Płaszczyznę w Górę <PgUp>", "Posuń Płaszczyznę w Dół <PgDown>", "Rail Gun", "Mutant bonus: zabijaj nie-mutantów przez dotykanie ich", "NULL", "Trampolina", "Blok Nieba", "Usuń z ekwipunku", "Miecz", "Zmień Drużyny",
			"Włączanie Obiektów", "Strzelba", "Miotacz Ognia", "Blok Pulsowania", "Randomizer", "Wyzwalanie Dźwięków", "Płaszczyzna Wody", "T-Pose", "Bezczynny", "Bieg",
			"Skok", "Umieranie", "Zrób zdjęcie awatara", "Resetuj awatar", "Pokój Kontroli", "Otwórz Sklep Ekwipunku", "Naciśnij M by pokazać Menu", "Puść TAB by ukryć Menu", "Naciśnij M by ukryć Menu", "Otwórz Sklep Awatarów",
			"Dodaj Kolekcje", "Rozłączono", "Połączono", "Dołączanie", "Dołączono", "Opuszczanie", "Rozłączanie", "Wyjątek", "CzasdoRozłączenia", "BlądWysyłania",
			"Dołączanie", "Pobieranie Materiałów", "Pobieranie Typów Przedmiotów", "Pobieranie Typów Własności", "Pobieranie Ekwipunku", "Pobieranie Sklepu Ekwipunku", "Pobieranie Sklepu Ekwipunku Awatarów", "Pobieranie Game Snapshot", "Pobieranie Listy Użytkowników", "Pobieranie Znajomych",
			"Pobieranie Listy Drużyn", "Wybieranie Drużyny", "Ustawianie Drużyn", "Pobieranie Streaming Assets", "Tworzenie Awatara", "Tworzenie Ciała Awatara", "Ustawianie Actor Gotowe", "Granie", "Opuszczanie", "Połączenie",
			"Gra", "Gracze: {0}", "Gracz", "Niebieska Drużyna", "Czerwona Drużyna", "Zielona Drużyna", "Żółta Drużyna", "Wynik", "Pobieranie Aktywnego Awatara", "{0} zabił {1} z {2}",
			"Center Gun", "Bazooka", "RailGun", "{} popełnił samobójstwo", "{0} uderzył w ziemie zbyt ciężko", "{0} został zabity przez otoczenie", "Miecz", "{0} został rozerwany na kawałki", "{0} spalony do śmierci", "{0} spadł ze świata",
			"Mutant", "Strzelba", "Miotacz Ognia", "{0} został zmiażdżony przez bloki", "{0} został zabity przez ducha", "Ten przedmiot nie może być użyty w tym typie gry.", "Ograniczony", "Jesteś pewien\nczy chcesz to usunąć?", "Ograniczony", "Zdjęcie Zrobione!",
			"To usunie wszelkie zmiany jakie zrobiłeś.\nJesteś pewien?", "Resetuj Awatar", "Wybierz Typ", "Typ", "Nie można utworzyć planu z 0 dziećmi.", "Błąd", "Usunąć Dziecko ?", "Usuń", "Float value", "Zmień Wartość",
			"Błąd analizacji nowej wartości", "Int Value", "String Value", "Usunąć Dane?", "Ponieważ przeglądasz ten przedmiot,\nzostanie on usunięty jeśli wyjdziesz.", "Dodaj Podgląd", "Kliknij \"Zdobądź Złoto\" na stronie\nby dodać więcej złota do twojego konta.", "Niewystarczające Fundusze", "Nie wystarczająco srebra by kupić produkt", "Nie wystarczająco funduszy by kupić produkt",
			"Wystąpił błąd:\n", "Nie jesteś autoryzowany by\nopublikować tą planete", "Pokaż Kontury", "Włączanie Obiektów", "Ukryj", "Ten dźwięk w tym wyzwalaniu dźwięków nie jest już dostępny.\nJeśli wybrałeś inny dźwięk, to nie możesz zmienić go z powrotem.", "Dostrzec", "Wybierz Modyfikator", "Modyfikator", "Prędkość",
			"Ruchoma Platforma", "Prędkość Obracania", "Rotator", "Raz", "Blok Wyzwalania", "Tylko jedna drużyna w świecie.", "Zmień Drużynę", "Proszę się Zarejestrować", "Zarejestruj się", "Projekt z planetId '{0}' nie istnieje",
			"Błąd z Internetem i/lub połączeniem bazą danych...", "Nie znaleziono serwerów gry!", "Nie można prosić znajomości siebie!", "Kupić Model ?", "Pełny Ekran nie jest obsługiwany w \nInternet Explorer version 8+.\n\nProszę użyć innej przeglądarki,\n by użyć pełnego ekranu.", "Tak", "Nie", "Ok", "Zapisz", "Odrzuć",
			"Anuluj", "Zapomniałeś o tych rzeczach:\n\nNie wpisano nazwy.\nNie wpisano woID.", "Zapomniałeś o tych rzeczach:\n\nNie wpisałeś nazwy.", "Zapomniałeś o tych rzeczach:\n\nNie wpisałeś woID.", "Sklep z Przedmiotami", "Sklep Awatarów", "Opublikuj Twoją Gre", "Sklep Materiałów", "Sklep dźwiękowy", "Kontynuuj",
			"Nie możesz usunąć ostatniego punktu spawnu.\nWszystkie Projekty muszą mieć przynajmniej jeden", "Zatwierdź", "Wyjątek Połączenia\nPołączyć ponownie?", "Utrata Połączenia.\nPołączyć ponownie?", "Połączenie Przeminęło.\nPołączyć ponownie?", "Przedmiot kupiony", "Niezdefiniowany błąd!", "Nie możesz kupić przedmiotu,\nponieważ jesteś właścicielem", "Przedmiot do kupna\nnie znaleziono", "Przedmiot już jest w twoim ekwipunku",
			"Pomyślnie dodano model do ekwipunku", "Nie udało się dodać do ekwipunku", "Nie udało się stworzyć przedmiotu", "Nie jesteś twórcą tego modelu.\n\nMożesz dodawać tylko modele do twojego ekwipunku, jeśli są stworzone przez ciebie", "Nie jesteś twórcą tego modelu.\n\nKup model by dodać go do twojego ekwipunku\nCena: {0} srebra", "Przedmiot już jest w twoim ekwipunku", "Prototyp nie znaleziono", "Nie jesteś autoryzowany by dołączyć do planety '{0}' w trybie edycji", "Pomyślnie opublikowano planetę", "Nie jesteś autoryzowany by opublikować tą planetę",
			"Unhandled returnCode", "Kupno", "Cena", "Proszę Czekać ...", "Podgląd", "Grawitacja", "Max Graczy", "Czas Rundy", "Przygoda", "Czat",
			"Współpraca", "Zdobądź Flagę", "Deathmatch", "Dotrzyj Do Flagi", "Próba Czasu", "Jesteś Pewien?", "Opublikuj Na Facebooka", "Poprzednia", "Następna", "Wybieranie Materiału",
			"Niebieski", "Zielony", "Czerwony", "Intensywność", "Zasięg", "Tekst", "Wielkość Tekstu", "Czas Wyłączenia", "Czas Włączenia", "Sekundy",
			"Mgła", "Kąt Słońca", "Wycisz", "Opóźnienie", "Trwanie", "Zmień", "Sklep", "Dołącz", "Gratulacje", "Zebrałeś wszystkie kolekcje!",
			"Zagraj Jeszcze Raz", "Chcesz zagrać jeszcze raz?", "Brak Wygranych", "Koniec Czasu", "Brak przedmiotów dostępnych do kupna", "Zaawansowane\nLogic", "Plan", "Logic", "Bonusy", "Modele\nPremium",
			"Nowy Model", "Wielkość", "Wróć", "Nie posiadasz żadnych Planów.\nZdobądź kilka ze sklepu!", "Nie posiadasz żadnych Modeli Premium.\nZdobądź kilka ze sklepu!", "Modele", "Naciśnij By Kontrolować ...", "Wyślij", "WiadomościGry", "Ustawienia",
			"Edytuj Model", "Usuń", "Klonuj", "Resetuj Logic", "Dodaj Do Ekwipunku", "Dodaj Nowy Awatar", "Był problem komunikacji z serwerem. Spróbuj jeszcze raz!", "Respawn Teraz!", "Respawn w", "Naciśnij",
			"by kupić", "Sklep Akcesoriów", "Ekwipunek Akcesoriów", "{0} nie udany rocketjump", "Produkt", "Pobieranie Statusu Credit", "Synchronizowanie Czasu Gry", "Opis", "Nazwa", "To usunie model z twojego ekwipunku",
			"Info", "Sprzedaj", "Zarządzaj", "Różnica Przedmiotów", "Sprzedaj Przedmiot", "Aktualizuj Przedmiot", "Usuń Przedmiot", "'{0}' jest teraz w markecie.", "Nie udało się umieścić '{0}' w markecie.", "Proszę się upewnić czy wszystkie wymagane informacje są wprowadzone",
			"Twój model nie jest wystarczająco inny w porównaniu do oryginalnego", "Porównywanie...", "'{0}' zaktualizowane w markecie.", "Nie udało się zaktualizować '{0}'.", "Usunięto '{0}' z marketu.", "Nie udało się usunąć '{0}' z marketu.", "Wynajmij", "Przedłuż", "{0} sekund", "{0} minut",
			"{0} godzin", "{0} dni", "{0} sek", "{0} min", "Czy chcesz przedłużyć?", "Przedmiot nie może być odnowiony i zostanie usunięty.", "Usuń", "Pobieranie Streaming Asset Ekwipunku", "Okres Wynajmu Upłynął", "Upłynął",
			"Nie posiadasz żadnych\nAkcesoriów Awatara.\n\nZdobądź kilka ze sklepu!", "Akcesoria\nAwatarów", "upłynął.", "Dlaczego nie zdobyć tego wspaniałego przedmiotu ze sklepu?", "Założyć awatarowi teraz?", "Produkt przeminął"
		}));
	}

	public string GetText(TextSlotIndex index)
	{
		string text = textCollections[cultureName].GetBaseString(index);
		if (text == null)
		{
			text = textCollections["en-US"].GetBaseString(index);
			if (text == null)
			{
				text = "Error : Localisation index does not exist";
			}
			else if (MVGameController.Instance.Game.IsDebugMode)
			{
				text = "Error : No localisation for culture " + cultureName + " exists for string '" + text + "'";
			}
		}
		return text;
	}

	public string GetText(string key_as_text)
	{
		TextSlotIndex textSlotIndex = TextSlotIndex.Empty;
		try
		{
			textSlotIndex = (TextSlotIndex)(int)Enum.Parse(typeof(TextSlotIndex), key_as_text);
		}
		catch
		{
			return "[localized key not found]";
		}
		string text = textCollections[cultureName].GetBaseString(textSlotIndex);
		if (text == null)
		{
			text = textCollections["en-US"].GetBaseString(textSlotIndex);
			if (text == null)
			{
				text = "Error : Localisation index does not exist";
			}
			else if (MVGameController.Instance.Game.IsDebugMode)
			{
				text = "Error : No localisation for culture " + cultureName + " exists for string '" + text + "'";
			}
		}
		return text;
	}

	public string[] GetTextAsList(TextSlotIndex index)
	{
		string text = textCollections[cultureName].GetBaseString(index);
		if (text == null)
		{
			text = textCollections["en-US"].GetBaseString(index);
			if (text == null)
			{
				text = "Error : Localisation index does not exist";
			}
			else if (MVGameController.Instance.Game.IsDebugMode)
			{
				text = "Error : No localisation for culture " + cultureName + " exists for string '" + text + "'";
			}
		}
		return text.Split(new char[2] { '{', '}' });
	}

	public string GetTextWithValues(TextSlotIndex index, ValueInsert values)
	{
		string text = textCollections[cultureName].GetBaseString(index);
		if (text == null)
		{
			text = textCollections["en-US"].GetBaseString(index);
			if (text == null)
			{
				text = "Error : Localisation index does not exist";
			}
			else if (MVGameController.Instance.Game.IsDebugMode)
			{
				text = "Error : No localisation for culture " + cultureName + " exists for string '" + text + "'";
			}
		}
		if (values != null)
		{
			text = string.Format(new CultureInfo(CultureName), text, values.GetValueParams());
		}
		return text;
	}
}
