public interface IWinningConditionBriefing
{
	void GetBriefing(MVGUIWinningConditionBriefingView winningConditionBriefingView);

	void GetDebriefing(MVGUIWinningConditionDebriefingView winningConditionDebriefingView);
}
