public enum PoolEnums
{
	CenterGunBullet = 0,
	CubeGunBullet = 1,
	SixShooterBullet = 2,
	BazookaBullet = 3,
	ShotgunBullet = 4,
	ThrowingStarBullet = 5,
	MultiThrowingStarBullet = 6,
	CubeGunRay = 7,
	RailGunRay = 8,
	ImpulseGunRay = 9,
	NormalBulletSparks = 10,
	SixShooterSparks = 11,
	XP = 12,
	AvatarBulletImpact = 13,
	VehicleBulletImpact = 14,
	BurningModifier = 15,
	MutantModifier = 16,
	PoisonModifier = 17,
	FrozenModifier = 18,
	NinjaRunModifier = 19,
	MouseModifier = 20,
	GrowthModifier = 21,
	InvulnerabilityModifier = 24,
	HealRaySparks = 25,
	LENGTH = 26
}
