public enum PoolEnums
{
	CenterGunBullet,
	CubeGunBullet,
	SixShooterBullet,
	BazookaBullet,
	ShotgunBullet,
	ThrowingStarBullet,
	MultiThrowingStarBullet,
	CubeGunRay,
	RailGunRay,
	ImpulseGunRay,
	NormalBulletSparks,
	SixShooterSparks,
	XP,
	AvatarBulletImpact,
	VehicleBulletImpact,
	LENGTH
}
